#!/bin/bash

vim_plugins=~/.vim/pack/my-plugins/start

# Install each of the dotfiles
find . -type d -mindepth 1 -maxdepth 1 | sed "s|^\./||" | xargs -I% stow %

# The following installs the vim helpdocs without messing up the terminal (both mac and gnu xargs)
find "$vim_plugins"  -type d -name doc | xargs -I% bash -c '</dev/tty vim --noplugin -u NONE -c "helptags %" -c q'
